import bedSheetImage from "../../assets/images/products/home/cotton-bed-sheet-set.jpg";
import knifeSetImage from "../../assets/images/products/home/kitchen-knife-set.jpg";
import cookwareImage from "../../assets/images/products/home/stainless-steel-cookware.jpg";
import pillowCoversImage from "../../assets/images/products/home/decorative-pillow-covers.jpg";
import homeImg from "../../assets/images/categories/homeImg.jpg";
import decorationImg from "../../assets/images/categories/decorationImg.jpg";

export const homeHeroCards = [
  { id: 1, title: "Monsoon", image: homeImg },
  { id: 2, title: "Cookware", image: cookwareImage },
  { id: 3, title: "Hardware", image: decorationImg },
  { id: 4, title: "Bathroom", image: homeImg },
  { id: 5, title: "Comforters", image: bedSheetImage },
  { id: 6, title: "Containers", image: homeImg },
  { id: 7, title: "Decor", image: pillowCoversImage },
  { id: 8, title: "Lighting", image: homeImg },
  { id: 9, title: "Lighting", image: homeImg },
  { id: 10, title: "Lighting", image: homeImg },
  { id: 11, title: "Lighting", image: homeImg },
  { id: 12, title: "Lighting", image: homeImg },
  { id: 13, title: "Lighting", image: homeImg },
  { id: 14, title: "Lighting", image: homeImg },
];

export const homeProducts = [
  {
    id: 1,
    slug: "cotton-bedsheet-set",
    title: "Cotton Bed Sheet Set",
    category: "Bedsheets",
    price: 1499,
    oldPrice: 2499,
    discountPercentage: 40,
    rating: 4.8,
    reviews: 128,
    featured: true,
    image: bedSheetImage,
    description: "Soft breathable cotton bed sheet set in vibrant colours.",
  },
  {
    id: 2,
    slug: "blackout-curtain-pair",
    title: "Blackout Curtain Pair",
    category: "Curtains",
    price: 1799,
    oldPrice: 2799,
    discountPercentage: 36,
    rating: 4.7,
    reviews: 96,
    featured: true,
    image: decorationImg,
    description: "Premium blackout curtains for better sleep and privacy.",
  },
  {
    id: 3,
    slug: "stainless-steel-cookware-set",
    title: "Stainless Steel Cookware Set",
    category: "Cookware",
    price: 3499,
    oldPrice: 4999,
    discountPercentage: 30,
    rating: 4.6,
    reviews: 214,
    featured: true,
    image: cookwareImage,
    description: "Durable 5-piece cookware set for daily kitchen use.",
  },
  {
    id: 4,
    slug: "kitchen-knife-cutting-board-set",
    title: "Kitchen Knife & Cutting Board Set",
    category: "Kitchen",
    price: 899,
    oldPrice: 1299,
    discountPercentage: 31,
    rating: 4.5,
    reviews: 87,
    featured: true,
    image: knifeSetImage,
    description: "Essential knife set with wooden cutting board for prep work.",
  },
  {
    id: 5,
    slug: "decorative-pillow-covers",
    title: "Decorative Pillow Covers",
    category: "Home Decor",
    price: 799,
    oldPrice: 1299,
    discountPercentage: 38,
    rating: 4.4,
    reviews: 73,
    featured: false,
    image: pillowCoversImage,
    description: "Set of stylish pillow covers to refresh your living room.",
  },
  {
    id: 6,
    slug: "canopy-mosquito-net",
    title: "Canopy Mosquito Net",
    category: "Mosquito Nets",
    price: 349,
    oldPrice: 599,
    discountPercentage: 42,
    rating: 4.3,
    reviews: 156,
    featured: false,
    image: homeImg,
    description: "Lightweight canopy mosquito net for comfortable nights.",
  },
  {
    id: 7,
    slug: "led-table-lamp",
    title: "LED Table Lamp",
    category: "Lighting",
    price: 499,
    oldPrice: 799,
    discountPercentage: 38,
    rating: 4.4,
    reviews: 112,
    featured: false,
    image: homeImg,
    description: "Energy-efficient LED lamp for bedside and study tables.",
  },
  {
    id: 8,
    slug: "spin-mop-bucket-set",
    title: "Spin Mop & Bucket Set",
    category: "Cleaning",
    price: 899,
    oldPrice: 1299,
    discountPercentage: 31,
    rating: 4.2,
    reviews: 189,
    featured: false,
    image: homeImg,
    description: "Easy-clean spin mop for quick floor cleaning.",
  },
  {
    id: 9,
    slug: "stackable-storage-box",
    title: "Stackable Storage Box",
    category: "Storage",
    price: 499,
    oldPrice: 799,
    discountPercentage: 38,
    rating: 4.1,
    reviews: 64,
    featured: false,
    image: homeImg,
    description: "Durable stackable boxes for seasonal storage and organisation.",
  },
  {
    id: 10,
    slug: "stainless-steel-spice-jar-set",
    title: "Stainless Steel Spice Jar Set",
    category: "Dining",
    price: 399,
    oldPrice: 599,
    discountPercentage: 33,
    rating: 4.3,
    reviews: 91,
    featured: false,
    image: homeImg,
    description: "Clear spice jars with labels for an organised kitchen.",
  },
];
